Fix macOS build (hopefully)

diff --git a/.github/scripts/utils.zsh/check_macos b/.github/scripts/utils.zsh/check_macos
--- a/.github/scripts/utils.zsh/check_macos
+++ b/.github/scripts/utils.zsh/check_macos
@@ -3,8 +3,8 @@ autoload -Uz is-at-least log_info log_error log_status read_codesign
 local macos_version=$(sw_vers -productVersion)
 
 log_info 'Checking macOS version...'
-if ! is-at-least 11.0 "${macos_version}"; then
-  log_error "Minimum required macOS version is 11.0, but running on macOS ${macos_version}"
+if ! is-at-least 13.0 "${macos_version}"; then
+  log_error "Minimum required macOS version is 13.0, but running on macOS ${macos_version}"
   return 2
 else
   log_status "macOS ${macos_version} is recent"
