macOS build

diff --git a/.github/scripts/utils.zsh/check_macos b/.github/scripts/utils.zsh/check_macos
--- a/.github/scripts/utils.zsh/check_macos
+++ b/.github/scripts/utils.zsh/check_macos
@@ -1,10 +1,11 @@
-autoload -Uz is-at-least log_info log_error log_status read_codesign
+autoload -Uz is-at-least log_group log_info log_error log_status read_codesign
 
 local macos_version=$(sw_vers -productVersion)
 
+log_group 'Install macOS build requirements'
 log_info 'Checking macOS version...'
-if ! is-at-least 13.0 "${macos_version}"; then
-  log_error "Minimum required macOS version is 13.0, but running on macOS ${macos_version}"
+if ! is-at-least 11.0 ${macos_version}; then
+  log_error "Minimum required macOS version is 11.0, but running on macOS ${macos_version}"
   return 2
 else
   log_status "macOS ${macos_version} is recent"
@@ -16,5 +17,10 @@ if (( ! ${+commands[brew]} )) {
   return 2
 }
 
-brew bundle --file "${SCRIPT_HOME}/.Brewfile"
+brew bundle --file ${SCRIPT_HOME}/.Brewfile
 rehash
+log_group
+
+log_group 'Build Boost and OpenSSL'
+${project_root}/.github/scripts/utils.zsh/macos-deps.zsh
+log_group
